import type { Metadata } from 'next'
import './globals.css'
import { Inter as FontSans } from 'next/font/google'
import { cn } from '@/lib/utils'
import Link from 'next/link'

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const links = [
  { href: '/', label: 'Home' },
  { href: '/docs', label: 'Docs' },
  { href: '/todos', label: 'Todos' },
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-backgrund font-sans antialiased',
          fontSans.variable
        )}
      >
        <header>
          <nav>
            <ul className="flex items-center ">
              {links.map(({ href, label }) => {
                return (
                  <li key={href} className="">
                    <Link href={href}>{label}</Link>
                  </li>
                )
              })}
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
